# <center> <u> Feature Selection </u> </center>

<h2>What's the Purpose of Feature Selection</h2>
<p>Many learning algorithms perform poorly on high-dimensional data. This is known as the <b>curse of dimensionality</b>
    <p>There are other reasons we may wish to reduce the number of features including:
        <p>1. Reducing computational cost
            <p>2. Reducing the cost associated with data collection
                <p>3. Improving Interpretability

# **`WATCH ALL VIDEOS IN THE PORTAL`**

## **`Watch Video 1: Feature Selection Techniques`**

File used: https://drive.google.com/file/d/1no82-mhXD52sQEu6I7-I6K5HPyVBIBgz/view?usp=sharing

Dataset : https://drive.google.com/file/d/1g3rLZpYb9BmBElDq_fo7F2nzpBuzaQYB/view?usp=sharing

**Problem Statement:**

Can you build a machine learning model to accurately predict whether or not the patients in the dataset have diabetes or not?

In [3]:
#import numpy, pandas 

import numpy as np
import pandas as pd


# import SelectFromModel, train_test_split, DecisionTreeClassifier, StandardScaler

import SelectFromModel,train_test_split,DecisionTreeClassifier,StandardScaler


# import RandomForestClassifier, roc_auc_score, StandardScaler, make_pipeline, KFold, KNeighborsRegressor


import RandomForestClassifier,roc_auc_score,make_pipeline,KFold,KNeighborsRegressor


import mean_squared_error, r2_score, cross_val_predict, LinearRegression, sqrt





# Note: just have a look what all libraries you have imported

ModuleNotFoundError: ignored

## 1.Filter Methods:



Filter method applies a statistical measure to assign a scoring to each feature.Then we can decide to keep or remove those features based on those scores. The methods are often univariate and consider the feature independently, or with regard to the dependent variable.

In this section we will cover below approaches:

1. Missing Value Ratio Threshold
2. Variance Threshold
3. $Chi^2$ Test
4. Anova Test

Download the dataset from https://github.com/arupbhunia/Data-Pre-processing/blob/master/datasets/diabetes.csv

Dataset used - diabetes.csv

Download instruction: go to the given link--->click raw button on top right corner---->Press Ctrl+S -->save it as .csv file.

## (a) Missing Value Ratio Threshold

<p style='text-align: right;'> 20 points</p>


Data Dict:
---

**Pregnancies:** Number of times pregnant <br>
**Glucose:** Plasma glucose concentration a 2 hours in an oral glucose tolerance test.<br>
**BloodPressure:** Diastolic blood pressure (mm Hg).<br>
**SkinThickness:** Triceps skin fold thickness (mm).<br>
**Insulin:** 2-Hour serum insulin (mu U/ml).<br>
**BMI:** Body mass index (weight in kg/(height in m)^2). <br>
**DiabetesPedigreeFunction:** A function which scores likelihood of diabetes based on family history<br>
**Age:** Age (years)<br>
**Outcome:** Class variable (0 or 1)

In [4]:
# create a data frame named diabetes and load the csv file

db = pd.read_csv("https://raw.githubusercontent.com/arupbhunia/Data-Pre-processing/master/datasets/diabetes.csv")
#print the head 
db.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

We know that some features can not be zero(e.g. a person's blood pressure can not be 0) hence we will impute zeros with nan value in these features.

Reference to impute: https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.DataFrame.replace.html

In [27]:
#Glucose BloodPressure, SkinThickness, Insulin, and BMI features cannot be zero ,we will impute zeros with nan value in these features.
db.replace(0,np.nan,inplace=True)
db.head(10)


db.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [10]:
#display the no of null values in each feature
db.isnull().sum()

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                     500
dtype: int64

Now let's see for each feature what is the percentage of having missing values.

In [12]:
#percentage of missing values for Glucose(sum null values , divide by length and multiply by 100)

db["Glucose"].isnull().sum()/len(db)*100

0.6510416666666667

In [14]:
# calculate the percentage for Bloodpressure
db["BloodPressure"].isnull().sum()/len(db)*100

4.557291666666666

In [15]:
# calculate the percentage for SkinThickness
db["SkinThickness"].isnull().sum()/len(db)*100

29.557291666666668

In [16]:
# calculate the percentage for Insulin
db["Insulin"].isnull().sum()/len(db)*100

48.69791666666667

In [17]:
# calculate the percentage for BMI

db["BMI"].isnull().sum()/len(db)*100

1.4322916666666665

Hey can you see that a large number of data missing in SkinThickness and Insulin.

## **`Watch Video 2: Identify and Dropping Missing Values`**

File used: https://drive.google.com/file/d/1xD7xnBXRYLGg5Qy8676lcj3QepoxmxMn/view?usp=sharing

Dataset: https://drive.google.com/file/d/18iVghbe09MKOMc49imA1Phuw-dNvMm4X/view?usp=sharing

Here we will keep only those features which are having missing data less than 10% as our threshold.


You can also check its document official: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html

In [33]:
#we are keep only those features which are having missing data less than 10% 
threshvalue =len(db)*0.9
diabetes_missing_value_threshold=db.dropna(thresh=threshvalue,axis=1)
diabetes_missing_value_threshold
# print diabetes_missing_value_threshold

     Glucose  BloodPressure   BMI  DiabetesPedigreeFunction  Age
0      148.0           72.0  33.6                     0.627   50
1       85.0           66.0  26.6                     0.351   31
2      183.0           64.0  23.3                     0.672   32
3       89.0           66.0  28.1                     0.167   21
4      137.0           40.0  43.1                     2.288   33
..       ...            ...   ...                       ...  ...
763    101.0           76.0  32.9                     0.171   63
764    122.0           70.0  36.8                     0.340   27
765    121.0           72.0  26.2                     0.245   30
766    126.0           60.0  30.1                     0.349   47
767     93.0           70.0  30.4                     0.315   23

[768 rows x 5 columns]

In [35]:
diabetes_missing_value_threshold['Outcome']=db['Outcome']
diabetes_missing_value_threshold['Outcome'].replace(np.nan,0,inplace=True)
diabetes_missing_value_threshold

<ipython-input-35-9c3b2534ba56>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diabetes_missing_value_threshold['Outcome']=db['Outcome']
<ipython-input-35-9c3b2534ba56>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diabetes_missing_value_threshold['Outcome'].replace(np.nan,0,inplace=True)

     Glucose  BloodPressure   BMI  DiabetesPedigreeFunction  Age  Outcome
0      148.0           72.0  33.6                     0.627   50      1.0
1       85.0           66.0  26.6                     0.351   31      0.0
2      183.0           64.0  23.3                     0.672   32      1.0
3       89.0           66.0  28.1                     0.167   21      0.0
4      137.0           40.0  43.1                     2.288   33      1.0
..       ...            ...   ...                       ...  ...      ...
763    101.0           76.0  32.9                     0.171   63      0.0
764    122.0           70.0  36.8                     0.340   27      0.0
765    121.0           72.0  26.2                     0.245   30      0.0
766    126.0           60.0  30.1                     0.349   47      1.0
767     93.0           70.0  30.4                     0.315   23      0.0

[768 rows x 6 columns]

In [36]:
diabetes_missing_value_threshold.head()

   Glucose  BloodPressure   BMI  DiabetesPedigreeFunction  Age  Outcome
0    148.0           72.0  33.6                     0.627   50      1.0
1     85.0           66.0  26.6                     0.351   31      0.0
2    183.0           64.0  23.3                     0.672   32      1.0
3     89.0           66.0  28.1                     0.167   21      0.0
4    137.0           40.0  43.1                     2.288   33      1.0

Let's now Seperate the data diabetes_missing_value_threshold into features and labels 

Hey buddy! label is something which is depen'dent on other features for its outcome. You can also called it as our Target variable which we predict using ML algorithms.

Can you think which column would be considered as label.

In [37]:

diabetes_missing_value_threshold_features = diabetes_missing_value_threshold.drop('Outcome',axis=1)

diabetes_missing_value_threshold_label= diabetes_missing_value_threshold['Outcome']

In [38]:
diabetes_missing_value_threshold_features

     Glucose  BloodPressure   BMI  DiabetesPedigreeFunction  Age
0      148.0           72.0  33.6                     0.627   50
1       85.0           66.0  26.6                     0.351   31
2      183.0           64.0  23.3                     0.672   32
3       89.0           66.0  28.1                     0.167   21
4      137.0           40.0  43.1                     2.288   33
..       ...            ...   ...                       ...  ...
763    101.0           76.0  32.9                     0.171   63
764    122.0           70.0  36.8                     0.340   27
765    121.0           72.0  26.2                     0.245   30
766    126.0           60.0  30.1                     0.349   47
767     93.0           70.0  30.4                     0.315   23

[768 rows x 5 columns]

In [39]:
diabetes_missing_value_threshold_label

0      1.0
1      0.0
2      1.0
3      0.0
4      1.0
      ...
763    0.0
764    0.0
765    0.0
766    1.0
767    0.0
Name: Outcome, Length: 768, dtype: float64

## (b) Variance Threshold

<p style='text-align: right;'> 20 points</p>

If the variance is low or close to zero, then a feature is approximately constant and will not improve the performance of the model. In that case, it should be removed.

Variance will also be very low for a feature if only a handful of observations of that feature differ from a constant value.

## **`Watch Video 3: Variance Threshold Removal`**

File used: https://drive.google.com/file/d/1aF_h1juJT6wY49ijjLh-7cMFxMkbXkt-/view?usp=sharing

Dataset used: https://drive.google.com/file/d/1-Sx-VZwuUYH8O48aw5mWYEXPLrLRlKKK/view?usp=sharing

Are you ready to implement feature selection using variance threshold? Smile and download the dataset diabetes_cleaned.csv from https://github.com/arupbhunia/Data-Pre-processing/blob/master/datasets/diabetes_cleaned.csv

Dataset used - diabetes_cleaned.csv

In [4]:
# load the csv to dataframe name "diabetes" and print the head values
dbc = pd.read_csv("https://raw.githubusercontent.com/arupbhunia/Data-Pre-processing/master/datasets/diabetes_cleaned.csv")

# print head
dbc.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,218.937760,33.6,0.627,50.0,1
1,1.0,85.0,66.0,29.0,70.189298,26.6,0.351,31.0,0
2,8.0,183.0,64.0,29.0,269.968908,23.3,0.672,32.0,1
3,1.0,89.0,66.0,23.0,94.000000,28.1,0.167,21.0,0
4,0.0,137.0,40.0,35.0,168.000000,43.1,2.288,33.0,1

In [5]:
# seperate the features and the target as x and y 
X =dbc.drop(columns=['Outcome'],axis=1)
Y=dbc['Outcome']

If you have seen the video then Krish must have told you to use sklearn library to calculate variance threshold. But we will use var function to calculate our variance so that you understand the concept from base.

In [6]:
# Return  the variance for X along the specified axis=0.

X.var(axis=0)

Pregnancies                   11.354056
Glucose                      929.680350
BloodPressure                146.321591
SkinThickness                 77.285567
Insulin                     9484.259268
BMI                           48.813618
DiabetesPedigreeFunction       0.109779
Age                          138.303046
dtype: float64

Hey smarty! did you see that DiabetesPedigreeFunction variance is less so it brings almost no information because it is (almost) constant , this can be a justification to remove DiabetesPedigreeFunction column but before considering this we should scale these features because they are of different scales.
    
Reference for minmax scaling: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

Lets use sklearn minmax scaler here.

In [7]:
from sklearn.preprocessing import MinMaxScaler


# use minmax scale with feature_range=(0,10) and columns=X.columns,to scale the features of dataframe and store them into X_scaled_df 
scaler =MinMaxScaler(feature_range=(0,10))
X_scaled_df=scaler.fit_transform(X)
X_scaled_df=pd.DataFrame(X_scaled_df,columns=X.columns)


Wait a minute! whats minmax scaling?

It is the simplest method and consists in rescaling the range of features to scale the range in [0, 1] or [−1, 1]

hey hey heyieeee! Fun fact time:

There is another scaling method called StandardScaler which follows Standard Normal Distribution (SND). Therefore, it makes mean = 0 and scales the data to unit variance. 

Cool right? :)

In [8]:
X_scaled_df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,3.529412,6.709677,4.897959,3.043478,2.740295,3.149284,2.344150,4.833333
1,0.588235,2.645161,4.285714,2.391304,1.018185,1.717791,1.165670,1.666667
2,4.705882,8.967742,4.081633,2.391304,3.331099,1.042945,2.536294,1.833333
3,0.588235,2.903226,4.285714,1.739130,1.293850,2.024540,0.380017,0.000000
4,0.000000,6.000000,1.632653,3.043478,2.150572,5.092025,9.436379,2.000000
...,...,...,...,...,...,...,...,...
763,5.882353,3.677419,5.306122,4.456522,2.289500,3.006135,0.397096,7.000000
764,1.176471,5.032258,4.693878,2.173913,2.044244,3.803681,1.118702,1.000000
765,2.941176,4.967742,4.897959,1.739130,1.502241,1.635992,0.713066,1.500000
766,0.588235,5.290323,3.673469,2.391304,2.217956,2.433538,1.157131,4.333333
767,0.588235,3.161290,4.693878,2.608696,1.215086,2.494888,1.011956,0.333333

In [21]:
# Again return  the variance for X along the specified axis=0 to check the scales after using minmax scaler.
X.var(axis=0)
X_scaled_df.var(axis=0)

Pregnancies                 3.928739
Glucose                     3.869637
BloodPressure               1.523548
SkinThickness               0.913109
Insulin                     1.271218
BMI                         2.041377
DiabetesPedigreeFunction    2.001447
Age                         3.841751
dtype: float64

Now again you can check the previous video

In [20]:
from sklearn.feature_selection import VarianceThreshold

selector = VarianceThreshold(1)
# set threshold=1 and define it to variable select_features
select_features = selector.fit(X_scaled_df)
select_features.get_support()

array([ True,  True,  True, False,  True,  True,  True,  True])

   Impliment fit_transform on select_features passing X_scaled_df into it and save this result in variable X_variance_threshold_df

In [ ]:
X_variance_threshold_df =

Were you thinking of fit_transform? We are here to help you understand

fit_transform() is used on the training data so that we can scale the training data and also learn the scaling parameters of that data. Here, the model built by us will learn the mean and variance of the features of the training set. These learned parameters are then used to scale our test data

Don't worry you will get lot of challenges to use these things in our other assignments

In [ ]:
#print X_variance_threshold_df

array([[3.52941176, 6.70967742, 4.89795918, ..., 3.14928425, 2.3441503 ,
        4.83333333],
       [0.58823529, 2.64516129, 4.28571429, ..., 1.71779141, 1.16567037,
        1.66666667],
       [4.70588235, 8.96774194, 4.08163265, ..., 1.04294479, 2.53629377,
        1.83333333],
       ...,
       [2.94117647, 4.96774194, 4.89795918, ..., 1.63599182, 0.71306576,
        1.5       ],
       [0.58823529, 5.29032258, 3.67346939, ..., 2.43353783, 1.15713066,
        4.33333333],
       [0.58823529, 3.16129032, 4.69387755, ..., 2.49488753, 1.01195559,
        0.33333333]])

In [11]:
#Convert X_variance_threshold_df into dataframe
X_variance_threshold_df =pd.DataFrame(select_features)

In [12]:
# print of head values of X_variance_threshold_df 

X_variance_threshold_df.head()

          0         1         2         3         4         5         6
0  3.529412  6.709677  4.897959  2.740295  3.149284  2.344150  4.833333
1  0.588235  2.645161  4.285714  1.018185  1.717791  1.165670  1.666667
2  4.705882  8.967742  4.081633  3.331099  1.042945  2.536294  1.833333
3  0.588235  2.903226  4.285714  1.293850  2.024540  0.380017  0.000000
4  0.000000  6.000000  1.632653  2.150572  5.092025  9.436379  2.000000

Below mentioned is the function get_selected_features for returning selected_features to be used further

In [14]:
def get_selected_features(raw_df,processed_df):
    selected_features=[]
    for i in range(len(processed_df.columns)):
        for j in range(len(raw_df.columns)):
            if (processed_df.iloc[:,i].equals(raw_df.iloc[:,j])):
                selected_features.append(raw_df.columns[j])
    return selected_features

In [17]:
# pass the X_scaled_df as raw_df and X_variance_threshold_df as processed_df inside get_selected_features function
selected_features = get_selected_features(X_scaled_df,X_variance_threshold_df)

# print selected_features
selected_features

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age']

Super! you can see SkinThickness feature is not selected as its variance is less.

Lets give column names to our X_variance_threshold_df

In [18]:
# define selected_features as columns and save it in variabe named X_variance_threshold_df
X_variance_threshold_df.columns =selected_features

#print X_variance_threshold_df

X_variance_threshold_df

,Pregnancies,Glucose,BloodPressure,Insulin,BMI,DiabetesPedigreeFunction,Age
0,3.529412,6.709677,4.897959,2.740295,3.149284,2.344150,4.833333
1,0.588235,2.645161,4.285714,1.018185,1.717791,1.165670,1.666667
2,4.705882,8.967742,4.081633,3.331099,1.042945,2.536294,1.833333
3,0.588235,2.903226,4.285714,1.293850,2.024540,0.380017,0.000000
4,0.000000,6.000000,1.632653,2.150572,5.092025,9.436379,2.000000
...,...,...,...,...,...,...,...
763,5.882353,3.677419,5.306122,2.289500,3.006135,0.397096,7.000000
764,1.176471,5.032258,4.693878,2.044244,3.803681,1.118702,1.000000
765,2.941176,4.967742,4.897959,1.502241,1.635992,0.713066,1.500000
766,0.588235,5.290323,3.673469,2.217956,2.433538,1.157131,4.333333
767,0.588235,3.161290,4.693878,1.215086,2.494888,1.011956,0.333333

## (c) Chi-Squared statistical test (SelectKBest)

<p style='text-align: right;'> 20 points</p>

Chi2 is a measure of dependency between two variables. It gives us a goodness of fit measure because it measures how well an observed distribution of a particular feature fits with the distribution that is expected if two features are independent.

Scikit-Learn offers a feature selection estimator named SelectKBest which select K numbers of features based on the statistical analysis.

Reference link: https://chrisalbon.com/machine_learning/feature_selection/chi-squared_for_feature_selection/

The below mentioned function generate_feature_scores_df is used to get feature score for using it in  Chi-Squared statistical test explained below

In [29]:
def generate_feature_scores_df(X,Score):
    feature_score=pd.DataFrame()
    for i in range(X.shape[1]):
        new =pd.DataFrame({"Features":X.columns[i],"Score":Score[i]},index=[i])
        feature_score=pd.concat([feature_score,new])
    return feature_score

Hey coder! lets use dataset - diabetes.csv from below link

https://github.com/arupbhunia/Data-Pre-processing/blob/master/datasets/diabetes.csv

In [22]:
# create a data frame named diabetes and load the csv file again
diabetes =pd.read_csv("https://raw.githubusercontent.com/arupbhunia/Data-Pre-processing/master/datasets/diabetes.csv")

In [23]:
# assign features to X variable and 'outcome' to y variable from the dataframe diabetes
X =diabetes.drop('Outcome',axis=1)
Y =diabetes['Outcome']

Reference Doc: https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectKBest.html

In [24]:
#import chi2 and SelectKBest

from sklearn.feature_selection import SelectKBest,chi2

In [26]:
# converting data cast to a float type.
X =X.astype(np.float64)
X.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0
1,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.0
2,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0

Lets use SelectKBest to calculate the best feature score. Use Chi2 as Score Function and no.of feature i.e. k as 4

In [27]:
# Initialise SelectKBest with above parameters 
chi2_test =SelectKBest(score_func=chi2,k=4)

# and fit it with X and Y
chi2_model =chi2_test.fit(X,Y)

In [31]:
#print the scores of chi2_model

chi2_model.scores_
chi2_model.feature_names_in_

array(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness',
       'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age'], dtype=object)

In [30]:
# use generate_feature_scores_df function to get features and their respective scores passing X and chi2_model.scores_ as paramter
feature_score_df = generate_feature_scores_df(X,chi2_model.scores_)
feature_score_df

                   Features        Score
0               Pregnancies   111.519691
1                   Glucose  1411.887041
2             BloodPressure    17.605373
3             SkinThickness    53.108040
4                   Insulin  2175.565273
5                       BMI   127.669343
6  DiabetesPedigreeFunction     5.392682
7                       Age   181.303689

Did you see the features and corresponding chi square scores? This is so easy right, higher the score better the feature. Just like higher the marks in assignment better the student of ours.

In [35]:
##Lets get X to the selected features of chi2_model using tranform function so we will have X_new

X_new =chi2_model.transform(X)
X_new

array([[148. ,   0. ,  33.6,  50. ],
       [ 85. ,   0. ,  26.6,  31. ],
       [183. ,   0. ,  23.3,  32. ],
       ...,
       [121. , 112. ,  26.2,  30. ],
       [126. ,   0. ,  30.1,  47. ],
       [ 93. ,   0. ,  30.4,  23. ]])

whaaaat! tranform()? , how is it different from fit_transform.You know buddy fit() can also confuse you. Hey you inquisitive learner we will tell you the difference.

The fit() function calculates the values of these parameters. The transform function applies the values of the parameters on the actual data and gives the normalized value. The fit_transform() function performs both in the same step. Note that the same value is got whether we perform in 2 steps or in a single step.

for more info on this refer below video

## **`Watch Video 4: Difference between fit transform fit_transform predict`**

File used: https://drive.google.com/file/d/1iD0XTSVo3DKdG5uO2H6MezvvmQ1TIm2B/view?usp=sharing

Dataset used: https://drive.google.com/file/d/1IIVkOAP6HYD4rQ-dqx7tRaVNCWxvxyE7/view?usp=sharing

In [37]:
# create a dataframe using X_new
X_new=pd.DataFrame(X_new)
X_new

         0      1     2     3
0    148.0    0.0  33.6  50.0
1     85.0    0.0  26.6  31.0
2    183.0    0.0  23.3  32.0
3     89.0   94.0  28.1  21.0
4    137.0  168.0  43.1  33.0
..     ...    ...   ...   ...
763  101.0  180.0  32.9  63.0
764  122.0    0.0  36.8  27.0
765  121.0  112.0  26.2  30.0
766  126.0    0.0  30.1  47.0
767   93.0    0.0  30.4  23.0

[768 rows x 4 columns]

In [38]:
#repeat the previous steps of calling get_selected_features function( pass X and X_new as score in the function)
selected_features = get_selected_features(X,X_new)
selected_features
# return selected_features

['Glucose', 'Insulin', 'BMI', 'Age']

Let have X with all features given in list selected_features and save this dataframe in variable chi2_best_features

In [39]:
# X with all features given in list selected_features 
chi2_best_features =X[selected_features]

# print chi2_best_features.head()
chi2_best_features.head()

   Glucose  Insulin   BMI   Age
0    148.0      0.0  33.6  50.0
1     85.0      0.0  26.6  31.0
2    183.0      0.0  23.3  32.0
3     89.0     94.0  28.1  21.0
4    137.0    168.0  43.1  33.0

As you can see chi-squared test helps us to select  important independent features out of the original features that have the strongest relationship with the target feature.

You did it well!

## (d) Anova-F Test

<p style='text-align: right;'> 20 points</p>

The F-value scores examine the varaiance by grouping the numerical feature by the target vector, the means for each group are significantly different.

## **`Watch Video 5: One Way ANOVA`**

File used: https://drive.google.com/file/d/1myYGdzEfmUqoWc0A3YNuK0oaId1_CCnI/view?usp=sharing

Dataset used: https://drive.google.com/file/d/1g50xZ7xqzHaXNoh0KuUyAaaui7i5ud8n/view?usp=sharing

In [42]:
from sklearn.feature_selection import f_classif,SelectPercentile 



# Initialise SelectPercentile function with parameters f_classif and percentile as 80
Anova_test = SelectPercentile(f_classif,percentile=80)

#Fit the above object to the features and target i.e X and Y
Anova_model= Anova_test.fit(X,Y)

here you have used f_classif for Anova-F test. To know more about this test you can check this artical.

https://towardsdatascience.com/anova-for-feature-selection-in-machine-learning-d9305e228476

In [44]:
# return scores of anova model
s=Anova_model.scores_

In [45]:
# use generate_feature_scores_df function to get features and their respective scores by passing X and Anova_model.scores_ as score in function 
feature_scores_df =generate_feature_scores_df(X,s)
feature_scores_df

                   Features       Score
0               Pregnancies   39.670227
1                   Glucose  213.161752
2             BloodPressure    3.256950
3             SkinThickness    4.304381
4                   Insulin   13.281108
5                       BMI   71.772072
6  DiabetesPedigreeFunction   23.871300
7                       Age   46.140611

In [46]:
# Get all supported columns values in Anova_model with indices=True
cols = Anova_model.get_support(indices=True)
# Reduce X to the selected features of anova model using tranform 
X_new = X.iloc[:,cols]

In [47]:
X_new.head()

   Pregnancies  Glucose  Insulin   BMI  DiabetesPedigreeFunction   Age
0          6.0    148.0      0.0  33.6                     0.627  50.0
1          1.0     85.0      0.0  26.6                     0.351  31.0
2          8.0    183.0      0.0  23.3                     0.672  32.0
3          1.0     89.0     94.0  28.1                     0.167  21.0
4          0.0    137.0    168.0  43.1                     2.288  33.0

Hey brighty! Hope you learned to implement Anova F-test method for feature selection. It has selected 6 best features as you can see in above output

# 2. Wrapper Methods

<p style='text-align: right;'> 30 points</p>

Wrapper methods are used to select a set of features by preparing where different combinations of features, then each combination is evaluated and compared to other combinations.Next a predictive model is used to assign a score based on model accuracy and to evaluate the combinations of these features.

In [48]:
# load and read the csv using pandas and print the head values

# print head
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [49]:
# assign features to X and target 'outcome' to Y(Think why the 'outcome' column is taken as the target)
X =diabetes.drop('Outcome',axis=1)
Y =diabetes['Outcome']
#return X,Y

## (a) Recursive Feature Elemination

<p style='text-align: right;'> 25 points</p>

Recursive Feature Elimination selects features by recursively considering smaller subsets of features by pruning the least important feature at each step. Here models are created iteartively and in each iteration it determines the best and worst performing features and this process continues until all the features are explored.Next ranking is given on eah feature based on their elimination orde. In the worst case, if a dataset contains N number of features RFE will do a greedy search for $N^2$ combinations of features.


## **`Watch Video 6: Recursive Feature Elimination`**

Note: the video is using random forest classifier, but we are going to use logistic regression as our model.

File used: https://drive.google.com/file/d/1NPomAlZP1g054xlRWUZ9_GE8pZxu2WFA/view?usp=sharing

Dataset used: https://drive.google.com/file/d/1WC4UwIx56Muc5lX3io7UJK_Is6gIv4tM/view?usp=sharing

In [52]:
# import required libraries RFE, LogisticRegression and dependencies
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [53]:
# Initialise model variable with LogisticRegression function with solver = 'liblinear'
model =LogisticRegression(solver = 'liblinear')

# rfe variable has RFE instance with should have model and n_features_to_select=4 as parameters
rfe = RFE(model,n_features_to_select=4)

In [54]:
# fit rfe with X and Y
fit = rfe.fit(X,Y)

In [62]:
# print fit.n_features_, fit.support_, fit.ranking_

fit.n_features_

4

In [59]:
# use below function to get ranks of all the features
def feature_ranks(X,Rank,Support):
    feature_rank=pd.DataFrame()
    for i in range(X.shape[1]):
        new =pd.DataFrame({"Features":X.columns[i],"Rank":Rank[i],'Selected':Support[i]},index=[i])
        feature_rank=pd.concat([feature_rank,new])
    return feature_rank

In [60]:
#Get all feature's ranks using feature_ranks function with suitable parameters in variable called feature_rank_df
feature_rank_df =feature_ranks(X, fit.ranking_,fit.support_)

# print feature_rank_df
feature_rank_df

                   Features  Rank  Selected
0               Pregnancies     1      True
1                   Glucose     1      True
2             BloodPressure     2     False
3             SkinThickness     4     False
4                   Insulin     5     False
5                       BMI     1      True
6  DiabetesPedigreeFunction     1      True
7                       Age     3     False

We can see there are four features with rank 1 ,RFE states that these are the most significant features.

In [66]:
# finally get all the features selected by RFE in dataframe X and this result in variable called RFE_selected_features
RFE_selected_features =X[recursive_feature_names["Features"].values]

# print RFE head()

RFE_selected_features

     Pregnancies  Glucose   BMI  DiabetesPedigreeFunction
0              6      148  33.6                     0.627
1              1       85  26.6                     0.351
2              8      183  23.3                     0.672
3              1       89  28.1                     0.167
4              0      137  43.1                     2.288
..           ...      ...   ...                       ...
763           10      101  32.9                     0.171
764            2      122  36.8                     0.340
765            5      121  26.2                     0.245
766            1      126  30.1                     0.349
767            1       93  30.4                     0.315

[768 rows x 4 columns]

In [69]:
recursive_feature_names["Features"].values

array(['Pregnancies', 'Glucose', 'BMI', 'DiabetesPedigreeFunction'],
      dtype=object)

In [61]:
# filter feature_rank_df  with selected column values as True and save it variable called recursive_feature_names 
recursive_feature_names = feature_rank_df.loc[feature_rank_df["Selected"]==True]

# print recursive_feature_names
recursive_feature_names

                   Features  Rank  Selected
0               Pregnancies     1      True
1                   Glucose     1      True
5                       BMI     1      True
6  DiabetesPedigreeFunction     1      True

# 3. Embedded Method using random forest

<p style='text-align: right;'> 25 points</p>

## **`Watch Video 7: Model based feature selection`**

File used: https://drive.google.com/file/d/1Vfmyrbz4HzRMtgYwasrHeXS7Zuo3Yk1b/view?usp=sharing

dataset : https://drive.google.com/file/d/1IyDpzY-9G5rO5sPsY0lN1o3hTzWNAPEY/view?usp=sharing

Feature selection using Random forest comes under the category of Embedded methods. Embedded methods combine the qualities of filter and wrapper methods. They are implemented by algorithms that have their own built-in feature selection methods. Some of the benefits of embedded methods are :
1. They are highly accurate.
2. They generalize better.
3. They are interpretable

In [70]:
#Importing libraries pd, RandomForestClassifier, SelectFromModel

from sklearn.ensemble import RandomForestClassifier
from  sklearn.feature_selection import SelectFromModel

In [71]:
# load the csv file using pandas and print the head values
diabetes.head() 

# print head

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In all feature selection procedures, it is a good practice to select the features by examining only the training set. This is to avoid overfitting.
So considering we have a train and a test dataset. We select the features from the train set and then transfer the changes to the test set later

In [73]:
from sklearn.model_selection import train_test_split 


# splitting of dataset(test_size=0.3)
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2,random_state=24)

Here We will do the model fitting and feature selection altogether in one line of code.

Firstly, specify the random forest instance, indicating the number of trees.

Then use selectFromModel object from sklearn to automatically select the features. Simple right?. Don't worry trust your code. It helps.

Reference link to use selectFromModel: https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectFromModel.html

In [74]:
#create an instance of Select from Model. Pass an object of Random Forest Classifier with n_estimators=100 as argument. 
sel = SelectFromModel(RandomForestClassifier(n_estimators=100))


# fit sel on X and y 
sel.fit(X_train,y_train)

SelectFromModel(estimator=RandomForestClassifier())

SelectFromModel will select those features which importance is greater than the mean importance of all the features by default, but we can alter this threshold if we want.

 To see which features are important we can use get_support method on the fitted model.

In [75]:
sel.get_support()

array([False,  True, False, False, False,  True,  True,  True])

In [78]:
#make a list named selected_feat with all columns which are True
selected_feat = X_train.columns[(sel.get_support())]

# print length of selected_feat
len(selected_feat)
X_train.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
280,0,146,70,0,0,37.9,0.334,28
528,0,117,66,31,188,30.8,0.493,22
569,0,121,66,30,165,34.3,0.203,33
495,6,166,74,0,0,26.6,0.304,66
638,7,97,76,32,91,40.9,0.871,32

In [79]:
# Print selected_feat
print(selected_feat)

Index(['Glucose', 'BMI', 'DiabetesPedigreeFunction', 'Age'], dtype='object')

Well done Champ!. Let us impliment SelectFromModel using LinearSVC model also

## Feature selection using SelectFromModel

<p style='text-align: right;'> 25 points</p>


SelectFromModel is a meta-transformer that can be used along with any estimator that has a coef_ or featureimportances attribute after fitting. The features are considered unimportant and removed, if the corresponding coef_ or featureimportances values are below the provided threshold parameter. Apart from specifying the threshold numerically, there are built-in heuristics for finding a threshold using a string argument. Available heuristics are “mean”, “median” and float multiples of these like “0.1*mean”.

Lets use selectfrommodel again with LinearSVC

In [80]:
# import libraries LinearSVC, SelectFromModel , and dependencies

from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel
from sklearn.svm import LinearSVC

In [81]:
#Use SelectFromModel with LinearSVC() as its parameter and save it in variable 'm'

m = SelectFromModel(LinearSVC())

# fit on X, y

m.fit(X,Y)

/usr/local/lib/python3.9/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

SelectFromModel(estimator=LinearSVC())

In [83]:
#make a list named selected_feat with all columns which are supported and count the selected features.

selected_feat = X_train.columns[(m.get_support())]

# print selected_feat
selected_feat

Index(['Pregnancies', 'DiabetesPedigreeFunction'], dtype='object')

 # 4. Handling Multicollinearity with VIF
 
 <p style='text-align: right;'> 15 points</p>

Multicollinearity refers to a situation in which more than two explanatory variables in a multiple regression model are highly linearly related. We have perfect multicollinearity if, for example as in the equation above, the correlation between two independent variables is equal to 1 or −1.

Variance inflation factor measures how much the behavior (variance) of an independent variable is influenced, or inflated, by its interaction/correlation with the other independent variables.

VIF has big defination but for now understand that:-
Variance inflation factor (VIF) is a measure of the amount of multicollinearity in a set of multiple regression variables

## **`Watch Video 8: Variance Inflation Factor`**

File : https://drive.google.com/file/d/1j1npRRM9iu_m61ElAdSHaP5mftNtGHQc/view?usp=sharing

In [84]:
#load and read the diabetes_cleaned.csv file using pandas and print the head values
dia_df = diabetes

# print dia_df
dia_df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [85]:
# describe the dataframe using .describe()
dia_df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

As we can see range of these features are very different that means they all are in different scales so lets standardize the features using sklearn's scale function.

reference doc: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.scale.html

In [86]:
#import variance inflation factor 
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [87]:

# split the data to test and train with test_size=0.2
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [89]:
#assign an empty dataframe to variable vif
vif =pd.DataFrame()

# make a new column 'VIF Factor' in vif dataframe and calculate the variance_inflation_factor for each X 
vif['VIF Factor'] = [variance_inflation_factor(X.values,i) for i in range(X.shape[1])]

In [90]:
# define vif['Features'] with columns names in X
vif['Features']=X.columns
vif

   VIF Factor                  Features
0    3.275748               Pregnancies
1   16.725078                   Glucose
2   14.619512             BloodPressure
3    4.008696             SkinThickness
4    2.063689                   Insulin
5   18.408884                       BMI
6    3.195626  DiabetesPedigreeFunction
7   13.492985                       Age

In [92]:
#  round off all the decimal values in the dataframe to 2 decimal places for VIF dataframe

vif=vif.round(2)
vif

   VIF Factor                  Features
0        3.28               Pregnancies
1       16.73                   Glucose
2       14.62             BloodPressure
3        4.01             SkinThickness
4        2.06                   Insulin
5       18.41                       BMI
6        3.20  DiabetesPedigreeFunction
7       13.49                       Age

* VIF = 1: Not correlated
* VIF =1-5: Moderately correlated
* VIF >5: Highly correlated

Glucose, Insulin, and Age are having large VIF scores, so lets drop it.

In [94]:
# according to above observation , drop  'Glucose', 'Insulin' and 'Age' from X
X = X.drop(['Glucose', 'BloodPressure', 'BMI'],axis=1)

Now again we calculate the VIF for the rest of the features

Again repeat the previous steps to assign an empty dataframe() to vif and make a new column 'VIF Factor' and calculate the variance_inflation_factorfor each X

In [96]:
# create an empty df

vif=pd.DataFrame()
# make a new column 'VIF Factor' and calculate the variance_inflation_factorfor each X
vif['VIF Factor'] = [variance_inflation_factor(X.values,i) for i in range(X.shape[1])]

In [97]:
#define vif['Features'] as columns of X and return vif with round off to 2 decimal places

vif['Features'] = X.columns

# round up to 2 
vif.round(2)

   VIF Factor                  Features
0        3.26               Pregnancies
1        2.95             SkinThickness
2        1.86                   Insulin
3        2.94  DiabetesPedigreeFunction
4        5.80                       Age

So now colinearity of features has been reduced using VIF.


The need to fix multicollinearity depends primarily on the below reasons:
---

1. When you care more about how much each individual feature rather than a group of features affects the target variable, then removing multicollinearity may be a good option

2. If multicollinearity is not present in the features you are interested in, then multicollinearity may not be a problem.

## **`Summary:`**

1. In the feature selection assignment, we learnt the methods which we use to find best features i.e. filter methods, wrapper methods and embedded methods.

2. In the filter methods, we learnt Chi2 test, Anova test, variance threshold and missing value ratio threshold.

3. In the wrapper method, we learnt forward selection, backward elimination and recursive feature elimination techniques.

4. In the embedded method, we create subsets of features and choose the best subset to train the model.

## **`Conclusion:`**
Feature selection is a very important step in the construction of Machine Learning models. <br>

It can speed up training time, make our models simpler, easier to debug, and reduce the time to market of Machine Learning products.

------------------------------

# Hip Hip Hurray! Congratulations you have completed the 7th assignment too! Very well done.

-------------------------------------

# Its Feedback Time!

We hope you’ve enjoyed this course so far. We’re committed to help you use "AI for All" course to its full potential, so that you have a great learning experience. And that’s why we need your help in form of a feedback here.


---
**Please fill this feedback form**<br>

https://forms.gle/VfxaKpjnmim8m4Yv8

------------------------------